name: Runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Update It
        run: |
          pip install -r requirements.txt
          python main.py
